// frontend-react/src/pages/ChangeAvatar.jsx
import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../api.js'
import './Theme.css'
import './ChangeAvatar.css'

export default function ChangeAvatar() {
  const [file, setFile] = useState(null)

  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  const [inputKey, setInputKey] = useState(0)

  async function uploadAvatar(e) {
    e.preventDefault()
    if (busy || !file) return

    setBusy(true)
    setError('')
    setSuccess('')

    // avatar upload is multipart, so we do not set content-type manually
    const formData = new FormData()
    formData.append('file', file)

    try {
      // apiFetch keeps auth headers consistent for protected endpoints
      const resp = await apiFetch('/api/user/avatar', {
        method: 'POST',
        body: formData,
      })

      if (!resp.ok) {
        // backend may return json {message/error}, fallback keeps it readable
        let msg = 'Error uploading image'
        try {
          const j = await resp.json()
          msg = j?.error || j?.message || msg
        } catch {}
        setError(typeof msg === 'string' && msg.trim() ? msg : 'Error uploading image')
        return
      }

      setSuccess('Avatar updated successfully.')
      setFile(null)

      // file inputs keep an internal value, so a key forces a clean visual reset
      setInputKey((k) => k + 1)
    } catch {
      setError('Network error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="cyber-page">
      <div className="cyber-wrap">
        <div className="cyber-panel ca-panel">
          <div className="ca-topbar">
            <h1 className="cyber-title">Change Profile Picture</h1>
            <div className="cyber-pill">Avatar</div>
          </div>

          <form className="ca-form" onSubmit={uploadAvatar} noValidate>
            <div className="ca-field">
              <label className="cyber-label" htmlFor="avatar">
                New Picture
              </label>

              <input
                key={inputKey}
                id="avatar"
                type="file"
                className="ca-file"
                accept="image/png, image/jpeg"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                required
              />

              <div className="ca-help text-muted">
                Must be less than 1 MiB in size and smaller than 3000 by 3000 pixels.
              </div>
            </div>

            <button type="submit" className="ca-btn ca-btn-cyan" disabled={busy || !file}>
              {busy ? 'Uploading…' : 'Upload'}
            </button>

            <Link to="/app/menu" className="ca-btn ca-btn-ghost">
              Return to Menu
            </Link>

            {error ? (
              <div className="ca-alert ca-alert-error card-glass" role="alert">
                {error}
              </div>
            ) : null}

            {success ? (
              <div className="ca-alert ca-alert-success card-glass" role="status">
                {success}
              </div>
            ) : null}
          </form>
        </div>
      </div>
    </div>
  )
}

// frontend-vue/src/views/ChangeAvatar.vue
<template>
  <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow" style="max-width: 400px; width: 100%">
      <h4 class="mb-3 text-center">Change Profile Picture</h4>

      <form @submit.prevent="uploadAvatar" novalidate>
        <div class="mb-3">
          <label class="form-label" for="avatar">New Picture</label>
          <input
            id="avatar"
            type="file"
            class="form-control"
            accept="image/png, image/jpeg"
            @change="onFileChange"
            required
          />
          <div class="form-text">
            Must be less than 1 MiB in size and smaller than 3000 by 3000 pixels.
          </div>
        </div>

        <button class="btn btn-primary w-100 mb-3" :disabled="busy || !file">Upload</button>
        <RouterLink to="/app/menu" class="btn btn-secondary w-100">Return to Menu</RouterLink>

        <div v-if="error" class="alert alert-danger mt-3" role="alert">{{ error }}</div>
        <div v-if="success" class="alert alert-success mt-3" role="alert">{{ success }}</div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { auth } from '../auth.js'

const file = ref(null)
const busy = ref(false)
const error = ref('')
const success = ref('')

function onFileChange(e) {
  const files = e.target.files
  if (files && files.length > 0) {
    file.value = files[0]
  } else {
    file.value = null
  }
}

async function uploadAvatar() {
  if (busy.value || !file.value) return
  busy.value = true
  error.value = ''
  success.value = ''

  const formData = new FormData()
  formData.append('file', file.value)

  try {
    const resp = await fetch('/api/user/avatar', {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + auth.token,
      },
      body: formData,
    })

    if (!resp.ok) {
      let msg = 'Error uploading image'
      try {
        const j = await resp.json()
        msg = j.error || msg
      } catch {}
      error.value = msg
      return
    }

    success.value = 'Avatar updated successfully.'
    file.value = null
  } catch (e) {
    error.value = 'Network error'
  } finally {
    busy.value = false
  }
}
</script>
