// frontend-react/src/pages/Login.jsx
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { auth } from '../auth.js'
import './Theme.css'
import './Login.css'

export default function Login() {
  const navigate = useNavigate()

  // form state
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  // ui state
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  async function login(e) {
    e.preventDefault()
    if (busy) return

    setBusy(true)
    setError('')

    try {
      const resp = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      })

      if (!resp.ok) {
        if (resp.status === 401) {
          setError('Bad credentials')
          return
        }

        try {
          const data = await resp.json()
          setError(data?.error || data?.message || `Error: ${resp.status}`)
        } catch {
          setError(`Error: ${resp.status} ${resp.statusText}`)
        }
        return
      }

      const data = await resp.json()
      auth.token = data.accessToken
      navigate('/app/menu')
    } catch {
      setError('Network error (CORS/connection)')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="cyber-page">
      <div className="cyber-wrap">
        <div className="cyber-panel login-panel">
          <div className="login-topbar">
            <h1 className="cyber-title">Login</h1>
            <div className="cyber-pill">JWT</div>
          </div>

          <form className="login-form" onSubmit={login} noValidate>
            <div className="login-field">
              <label className="cyber-label" htmlFor="email">
                E-Mail Address
              </label>
              <input
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value.trim())}
                type="email"
                className="cyber-input"
                required
                autoComplete="email"
                placeholder="you@example.com"
              />
            </div>

            <div className="login-field">
              <label className="cyber-label" htmlFor="password">
                Password
              </label>
              <input
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                type="password"
                className="cyber-input"
                required
                autoComplete="current-password"
                placeholder="••••••••"
              />
            </div>

            <button type="submit" className="btn-magenta login-btn" disabled={busy}>
              {busy ? 'Logging in…' : 'Login'}
            </button>

            <Link to="/app/menu" className="btn-ghost login-btn login-link">
              Return to Menu
            </Link>

            {error ? (
              <div className="login-error card-glass" aria-live="polite">
                {error}
              </div>
            ) : null}
          </form>
        </div>
      </div>
    </div>
  )
}

// frontend-vue/src/views/Login.vue
<template>
  <div class="container py-5" style="max-width: 420px">
    <h2 class="mb-3">Login (JWT)</h2>

    <form @submit.prevent="login" novalidate>
      <div class="mb-3">
        <label class="form-label">E-Mail Address</label>
        <input
          v-model.trim="email"
          type="email"
          class="form-control"
          required
          autocomplete="email"
        />
      </div>

      <div class="mb-3">
        <label class="form-label">Password</label>
        <input
          v-model="password"
          type="password"
          class="form-control"
          required
          autocomplete="current-password"
        />
      </div>

      <button class="btn btn-primary w-100 mb-3" :disabled="busy">Login</button>
      <RouterLink to="/app/menu" class="btn btn-secondary w-100">Return to Menu</RouterLink>

      <div v-if="error" class="text-danger small mt-2" aria-live="polite">{{ error }}</div>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { auth } from '../auth.js'

const router = useRouter()
const email = ref('')
const password = ref('')
const busy = ref(false)
const error = ref('')

async function login() {
  if (busy.value) return
  busy.value = true
  error.value = ''
  try {
    const resp = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email.value, password: password.value }),
    })

    if (!resp.ok) {
      if (resp.status === 401) {
        error.value = 'Bad credentials'
        return
      }
      //other errors
      try {
        const data = await resp.json()
        error.value = data?.error || data?.message || `Error: ${resp.status}`
      } catch {
        error.value = `Error: ${resp.status} ${resp.statusText}`
      }
      return
    }

    const data = await resp.json() // { accessToken, expiresIn }
    auth.token = data.accessToken
    router.push('/app/menu')
  } catch (e) {
    //only real network/CORS problems are handled here
    error.value = 'Network error (CORS/connnection)'
  } finally {
    busy.value = false
  }
}
</script>
