// frontend-react/src/pages/Menu.jsx
// frontend-react/src/pages/Menu.jsx
// main menu using the shared cyber theme and a compact action layout

import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { auth } from '../auth.js'
import './Theme.css'
import './Menu.css'

export default function Menu() {
  const navigate = useNavigate()
  const [isLoggedIn, setIsLoggedIn] = useState(!!auth.token)

  useEffect(() => {
    setIsLoggedIn(!!auth.token)
  }, [])

  function logout() {
    auth.logout()
    setIsLoggedIn(false)
    navigate('/app/menu')
  }

  return (
    <div className="cyber-page">
      <div className="cyber-wrap">
        <div className="cyber-panel menu-panel">
          <div className="menu-topbar">
            <h1 className="cyber-title">Pong</h1>
            <div className="cyber-pill">{isLoggedIn ? 'Logged in' : 'Guest'}</div>
          </div>

          {isLoggedIn ? (
            <div className="menu-actions">
              <Link to="/app/game" className="menu-btn menu-btn-primary">
                Play Pong
              </Link>

              <Link to="/app/leaderboard" className="menu-btn menu-btn-ghost">
                Leaderboard
              </Link>

              <div className="menu-row">
                <Link to="/app/change-password" className="menu-btn menu-btn-warn">
                  Change Password
                </Link>
                <Link to="/app/change-avatar" className="menu-btn menu-btn-cyan">
                  Change Profile Picture
                </Link>
              </div>

              <button type="button" onClick={logout} className="menu-btn menu-btn-danger">
                Logout
              </button>
            </div>
          ) : (
            <div className="menu-actions">
              <Link to="/app/signup" className="menu-btn menu-btn-primary">
                Sign Up
              </Link>

              <Link to="/app/login" className="menu-btn menu-btn-ghost">
                Sign In
              </Link>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend-vue/src/views/Menu.vue
<template>
  <div class="container text-center py-5" style="max-width: 400px">
    <h1 class="display-4 mb-4">Pong</h1>

    <div v-if="isLoggedIn">
      <div class="alert alert-success" role="alert">You are logged in.</div>

      <div class="d-grid gap-3 mx-auto">
        <RouterLink to="/app/game" class="btn btn-success btn-lg py-3"> Play Pong </RouterLink>
        <RouterLink to="/app/leaderboard" class="btn btn-primary btn-lg py-3">
          Leaderboard
        </RouterLink>

        <div class="d-flex gap-2">
          <RouterLink to="/app/change-password" class="btn btn-outline-warning w-50">
            Change Password
          </RouterLink>
          <RouterLink to="/app/change-avatar" class="btn btn-outline-info w-50">
            Change Profile Picture
          </RouterLink>
        </div>

        <button @click="logout" class="btn btn-outline-danger">Logout</button>
      </div>
    </div>

    <div v-else>
      <div class="d-grid gap-3 mx-auto">
        <RouterLink to="/app/signup" class="btn btn-primary btn-lg d-block w-100 mb-3">
          Sign Up
        </RouterLink>
        <RouterLink to="/app/login" class="btn btn-success btn-lg d-block w-100 mb-3">
          Sign In
        </RouterLink>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { auth } from '../auth.js'

const router = useRouter()

// Create a reactive state so Vue knows when to update the DOM
const isLoggedIn = ref(!!auth.token)

function logout() {
  auth.logout()
  isLoggedIn.value = false // Trigger the view update instantly
  router.push('/app/menu') // Ensure URL is correct (redundant but safe)
}
</script>
