// frontend-vue/src/views/ChangePassword.vue
<template>
  <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow" style="max-width: 400px; width: 100%">
      <h4 class="mb-3 text-center">Change Password</h4>

      <form @submit.prevent="changePassword" novalidate>
        <div class="mb-3">
          <label class="form-label" for="oldPassword">Old Password</label>
          <input
            id="oldPassword"
            v-model="oldPassword"
            type="password"
            class="form-control"
            required
          />
        </div>
        <div class="mb-3">
          <label class="form-label" for="newPassword">New Password</label>
          <input
            id="newPassword"
            v-model="newPassword"
            type="password"
            class="form-control"
            required
          />
        </div>

        <button class="btn btn-warning w-100 mb-3" :disabled="busy">Change Password</button>
        <RouterLink to="/app/menu" class="btn btn-secondary w-100">Return to Menu</RouterLink>

        <div v-if="error" class="alert alert-danger mt-3" role="alert">{{ error }}</div>
        <div v-if="success" class="alert alert-success mt-3" role="alert">{{ success }}</div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { auth } from '../auth.js'

const oldPassword = ref('')
const newPassword = ref('')
const busy = ref(false)
const error = ref('')
const success = ref('')

async function changePassword() {
  if (busy.value) return
  busy.value = true
  error.value = ''
  success.value = ''

  try {
    const resp = await fetch('/api/user/change_password', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + auth.token,
      },
      body: JSON.stringify({
        oldPassword: oldPassword.value,
        newPassword: newPassword.value,
      }),
    })

    if (!resp.ok) {
      let msg = 'Error changing password'
      try {
        const j = await resp.json()
        msg = j.error || msg
      } catch {}
      error.value = msg
      return
    }

    success.value = 'Password changed successfully.'
    oldPassword.value = ''
    newPassword.value = ''
  } catch (e) {
    error.value = 'Network error'
  } finally {
    busy.value = false
  }
}
</script>

// frontend-react/src/pages/ChangePassword.jsx
import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../api.js'
import './Theme.css'
import './ChangePassword.css'

export default function ChangePassword() {
  const [oldPassword, setOldPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')

  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  async function changePassword(e) {
    e.preventDefault()
    if (busy) return

    setBusy(true)
    setError('')
    setSuccess('')

    try {
      // apiFetch keeps auth headers consistent across protected endpoints
      const resp = await apiFetch('/api/user/change_password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ oldPassword, newPassword }),
      })

      if (!resp.ok) {
        // backend sometimes returns json {message/error}, fallback keeps it readable
        let msg = 'Error changing password'
        try {
          const j = await resp.json()
          msg = j?.error || j?.message || msg
        } catch {}
        setError(typeof msg === 'string' && msg.trim() ? msg : 'Error changing password')
        return
      }

      setSuccess('Password changed successfully.')
      setOldPassword('')
      setNewPassword('')
    } catch {
      // catches fetch/network/cors issues, not backend validation
      setError('Network error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="cyber-page">
      <div className="cyber-wrap">
        <div className="cyber-panel cp-panel">
          <div className="cp-topbar">
            <h1 className="cyber-title">Change Password</h1>
            <div className="cyber-pill">Account</div>
          </div>

          <form className="cp-form" onSubmit={changePassword} noValidate>
            <div className="cp-field">
              <label className="cyber-label" htmlFor="oldPassword">
                Old Password
              </label>
              <input
                id="oldPassword"
                value={oldPassword}
                onChange={(e) => setOldPassword(e.target.value)}
                type="password"
                className="cyber-input"
                autoComplete="current-password"
                required
              />
            </div>

            <div className="cp-field">
              <label className="cyber-label" htmlFor="newPassword">
                New Password
              </label>
              <input
                id="newPassword"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                type="password"
                className="cyber-input"
                autoComplete="new-password"
                required
              />
            </div>

            <button type="submit" className="cp-btn cp-btn-warn" disabled={busy}>
              {busy ? 'Changing…' : 'Change Password'}
            </button>

            <Link to="/app/menu" className="cp-btn cp-btn-ghost">
              Return to Menu
            </Link>

            {error ? (
              <div className="cp-alert cp-alert-error card-glass" role="alert">
                {error}
              </div>
            ) : null}

            {success ? (
              <div className="cp-alert cp-alert-success card-glass" role="status">
                {success}
              </div>
            ) : null}
          </form>
        </div>
      </div>
    </div>
  )
}
